name: DarthSky
options:
  bundleIdPrefix: com.darthsky
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    ENABLE_PREVIEWS: true

targets:
  DarthSky:
    type: application
    platform: iOS
    sources:
      - DarthSky
      - Shared
    settings:
      base:
        INFOPLIST_FILE: DarthSky/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.darthsky.weather
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE: true
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: true
        INFOPLIST_KEY_CFBundleDisplayName: "Darth Sky"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.weather"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Darth Sky uses your location to show weather conditions for where you are."
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    entitlements:
      path: DarthSky/Resources/DarthSky.entitlements
    dependencies:
      - target: DarthSkyWidgets

  DarthSkyWidgets:
    type: app-extension
    platform: iOS
    sources:
      - DarthSkyWidgets
      - Shared
      - path: DarthSky/Models
      - path: DarthSky/Services
      - path: DarthSky/Utilities
      - path: DarthSky/Extensions
    settings:
      base:
        INFOPLIST_FILE: DarthSkyWidgets/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.darthsky.weather.widgets
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: true
        SKIP_INSTALL: true
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: DarthSkyWidgets/Resources/DarthSkyWidgets.entitlements
